baseURL = "https://pallahaxi.github.io/calender_deriven_development/"
languageCode = "ja-jp"
title = "Juliaで数理最適化"
theme = "book"
publishDir = "docs"
canonifyurls = true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Python言語による実務で使える100+の最適化問題"
  url = "https://mikiokubo.github.io/opt100/index.html"
  weight = 10
